import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import {
  DealType,
  Footer,
  PropertyCarousel,
  Searchbar,
  TopMenu,
} from '@app/components';
import type { PropertyCardProps } from '@app/components';
import { HCenter } from '@app/containers/HCenter';
import { generateProperties } from '@app/utils/demo';
import styles from '@app/styles/pages/Home.module.scss';

const Home: NextPage = () => {
  const [propertiesAroundMe, setPropertiesAroundMe] = useState<PropertyCardProps[]>([]);
  const [matchedProperties, setMatchedProperties] = useState<PropertyCardProps[]>([]);
  const [recentlyViewedProperties, setRecentlyViewedProperties] = useState<PropertyCardProps[]>([]);

  useEffect(() => {
    setPropertiesAroundMe(generateProperties(10));
    setMatchedProperties(generateProperties(10));
    setRecentlyViewedProperties(generateProperties(10));
  }, [])

  return (
    <>
      <Head>
        <title>Test Components Now</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <TopMenu
          locale="EN/EN"
        />
        <section className={classNames("min-h-[11.25rem] overflow-auto", styles.topImgContainer)}>
          <HCenter><DealType className="mt-[7.125rem] mb-3" /></HCenter>
          <HCenter><Searchbar /></HCenter>
        </section>

        <section className="max-w-[66.125rem] mx-auto">
          <PropertyCarousel
            className="mt-[5.5rem]"
            label="Properties around me"
            properties={propertiesAroundMe}
          />
          <PropertyCarousel
            className="mt-[7.5rem]"
            label="Matched Properties"
            properties={matchedProperties}
          />
          <PropertyCarousel
            className="mt-[7.5rem]"
            label="Properties recently viewed"
            properties={recentlyViewedProperties}
          />
        </section>

      </main>
      <Footer />
    </>
  )
}

export default Home
