import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import {
  DealType,
  Footer,
  PropertyCarousel,
  RewardCard,
  Searchbar,
  TopMenu,
} from '@app/components';
import type {
  PropertyCardProps,
  RewardCardProps,
} from '@app/components';
import { HCenter } from '@app/containers/HCenter';
import {
  generateProperties,
  getRewardCardData
} from '@app/utils/demo';
import styles from '@app/styles/pages/Home.module.scss';

const Home: NextPage = () => {
  const [propertiesAroundMe, setPropertiesAroundMe] = useState<PropertyCardProps[]>([]);
  const [matchedProperties, setMatchedProperties] = useState<PropertyCardProps[]>([]);
  const [recentlyViewedProperties, setRecentlyViewedProperties] = useState<PropertyCardProps[]>([]);
  const [rewardCardData, setRewardCardData] = useState<RewardCardProps[]>([]);

  useEffect(() => {
    setPropertiesAroundMe(generateProperties(10));
    setMatchedProperties(generateProperties(10));
    setRecentlyViewedProperties(generateProperties(10));
    setRewardCardData(getRewardCardData());
  }, [])

  return (
    <>
      <Head>
        <title>Test Components Now</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <TopMenu
          locale="EN/EN"
        />
        <section className={classNames("min-h-[11.25rem] overflow-auto", styles.topImgContainer)}>
          <HCenter><DealType className="mt-[7.125rem] mb-3" /></HCenter>
          <HCenter><Searchbar /></HCenter>
        </section>

        <section className="max-w-[66.125rem] mx-auto">
          <PropertyCarousel
            className="mt-[5.5rem]"
            label="Properties around me"
            properties={propertiesAroundMe}
          />
          <PropertyCarousel
            className="mt-[7.5rem]"
            label="Matched Properties"
            properties={matchedProperties}
          />
          <PropertyCarousel
            className="mt-[7.5rem]"
            label="Properties recently viewed"
            properties={recentlyViewedProperties}
          />
          <section className="mt-[6.5rem]">
            <p className="font-medium text-xl leading-2xl text-secondary-1">Featured Services</p>
            <div className="flex justify-between mt-[4.25rem] gap-[2rem]">
              {
                rewardCardData.map(data =>
                  <RewardCard
                    className="w-1/4"
                    {...data}
                  />
                )
              }
            </div>
          </section>
        </section>
      </main>
      <Footer />
    </>
  )
}

export default Home
