import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { DatePicker } from 'antd'
import { useGetPostQuery } from '../graphql/types'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data, error, loading } = useGetPostQuery();
  data?.getPosts?.map
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          {loading && "Loading"}
          {error && "Error happened!"}
        </p>

        <div>
          <DatePicker />
        </div>

        <div className={styles.grid}>
          {data && data.getPosts?.map(post => (
            <a
              key={post?.id}
              href="https://nextjs.org/docs"
              className={styles.card}
            >
              <h2>{post?.id} &rarr;</h2>
              <p>{post?.body}</p>
            </a>
          ))}

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
